"""Column definitions, categories, and validation rules for seed data.

컬럼 정의, 카테고리, 검증 규칙 시드 데이터.
이 파일에서 공정조건표의 컬럼 구조(~350개)와 입력값 검증 규칙(~80개)을 정의한다.
컬럼을 추가/수정하려면 COLUMN_DEFS 리스트를, 검증 규칙을 변경하려면 VALIDATION_RULES를 수정한다.
"""

# ---------------------------------------------------------------------------
# 1. 컬럼 카테고리 & 정의 (350개 컬럼)
# ---------------------------------------------------------------------------

# 카테고리 목록: 조건표 컬럼을 4개 탭으로 그룹핑
# category_code: 컬럼명 접두사와 일치 (SP_xxx, SC_xxx 등)
# sort_order: 편집기 UI에서 탭 표시 순서
CATEGORIES = [
    {"category_code": "SP", "category_name": "Spin / PR", "sort_order": 1},
    {"category_code": "SC", "category_name": "Scanner / Expose", "sort_order": 2},
    {"category_code": "OVL", "category_name": "Overlay", "sort_order": 3},
    {"category_code": "DEV", "category_name": "Develop", "sort_order": 4},
    # EQP 카테고리: 레이어별 설비(스캐너) 할당 관리 (조건 JSONB 내에 컬럼으로 저장)
    {"category_code": "EQP", "category_name": "Equipment", "sort_order": 5},
]

# 스캐너(노광장비) 선택 옵션: SC_TOOL_ID 컬럼의 드롭다운에서 표시됨
# 새로운 스캐너 장비를 추가할 때 이 리스트에 추가
SCANNER_TOOL_OPTIONS = [
    "NSR-S322F-01", "NSR-S322F-02", "NSR-S322F-03",
    "NSR-S631E-01", "XT-1400E-01",
    "XT-1900Gi-01", "XT-1900Gi-02", "NXT-2000-01",
    "EUV-3400-01", "EUV-3400-02",
]

# 컬럼 정의 튜플 구조:
# (column_name,   - DB 저장용 컬럼 키 (JSONB의 키로 사용됨, 접두사가 카테고리 코드)
#  display_name,  - 화면 표시명 (AG Grid 헤더에 표시)
#  category_code, - 소속 카테고리 (SP/SC/OVL/DEV)
#  data_type,     - 데이터 타입 (string/integer/float/select/layer_ref)
#  unit,          - 단위 (nm, rpm, mJ 등, 없으면 None)
#  is_required,   - 필수 입력 여부 (True면 빈값 시 검증 오류)
#  select_options) - select 타입일 때 선택 가능한 값 목록 (없으면 None)
COLUMN_DEFS: list[tuple] = [
    # -----------------------------------------------------------------------
    # SP 카테고리 (~85개 컬럼): 포토레지스트(PR) 도포 공정 파라미터
    # PR 종류, 스핀 속도, 베이크 온도/시간, 접착층(HMDS), BARC/TARC 등
    # -----------------------------------------------------------------------
    # --- 기존 20개 SP 컬럼 ---
    ("SP_PR_TYPE", "PR Type", "SP", "select", None, True,
     ["KrF-A01", "KrF-B02", "ArF-C01", "ArF-D01", "EUV-E01"]),
    ("SP_PR_VENDOR", "PR Vendor", "SP", "select", None, False,
     ["TOK", "JSR", "Shin-Etsu", "Fujifilm", "DuPont"]),
    ("SP_PR_VISCOSITY_cP", "PR Viscosity", "SP", "float", "cP", False, None),
    ("SP_DISPENSE_VOL_ml", "Dispense Vol", "SP", "float", "ml", True, None),
    ("SP_SPIN1_SPEED_rpm", "Spin1 Speed", "SP", "integer", "rpm", True, None),
    ("SP_SPIN1_TIME_sec", "Spin1 Time", "SP", "integer", "s", True, None),
    ("SP_SPIN2_SPEED_rpm", "Spin2 Speed", "SP", "integer", "rpm", False, None),
    ("SP_SPIN2_TIME_sec", "Spin2 Time", "SP", "integer", "s", False, None),
    ("SP_EBR_SPEED_rpm", "EBR Speed", "SP", "integer", "rpm", False, None),
    ("SP_PREBAKE_TEMP_C", "Prebake Temp", "SP", "integer", "\u2103", True, None),
    ("SP_PREBAKE_TIME_sec", "Prebake Time", "SP", "integer", "s", True, None),
    ("SP_PR_THICKNESS_nm", "PR Thickness", "SP", "integer", "nm", False, None),
    ("SP_ADHESION_USE", "Adhesion Use", "SP", "select", None, True, ["Y", "N"]),
    ("SP_ADHESION_TYPE", "Adhesion Type", "SP", "select", None, False,
     ["HMDS", "HMDS-V2", "AP3000", "NONE"]),
    ("SP_ADHESION_TEMP_C", "Adhesion Temp", "SP", "integer", "\u2103", False, None),
    ("SP_COOL_TEMP_C", "Cool Temp", "SP", "integer", "\u2103", False, None),
    ("SP_COOL_TIME_sec", "Cool Time", "SP", "integer", "s", False, None),
    ("SP_COAT_METHOD", "Coat Method", "SP", "select", None, False,
     ["SPIN", "SPRAY", "SLIT"]),
    ("SP_HUMIDITY_PCT", "Humidity", "SP", "float", "%", False, None),
    ("SP_BACKSIDE_RINSE", "Backside Rinse", "SP", "select", None, False, ["Y", "N"]),
    # --- 추가 SP 컬럼 (~65개): BARC/TARC, 이중 코팅, 엣지 처리, 분사 조건 등 ---
    ("SP_BARC_USE", "BARC Use", "SP", "select", None, False, ["Y", "N"]),
    ("SP_BARC_TYPE", "BARC Type", "SP", "select", None, False,
     ["ARC-29A", "ARC-40A", "ARC-29B", "DBARC-11", "NONE"]),
    ("SP_BARC_THICKNESS_nm", "BARC Thickness", "SP", "float", "nm", False, None),
    ("SP_BARC_BAKE_TEMP_C", "BARC Bake Temp", "SP", "integer", "\u2103", False, None),
    ("SP_BARC_BAKE_TIME_sec", "BARC Bake Time", "SP", "integer", "s", False, None),
    ("SP_TARC_USE", "TARC Use", "SP", "select", None, False, ["Y", "N"]),
    ("SP_TARC_TYPE", "TARC Type", "SP", "select", None, False,
     ["TARC-101", "TARC-S01", "NONE"]),
    ("SP_TARC_THICKNESS_nm", "TARC Thickness", "SP", "float", "nm", False, None),
    ("SP_TARC_BAKE_TEMP_C", "TARC Bake Temp", "SP", "integer", "\u2103", False, None),
    ("SP_TARC_BAKE_TIME_sec", "TARC Bake Time", "SP", "integer", "s", False, None),
    ("SP_DUAL_COAT_USE", "Dual Coat Use", "SP", "select", None, False, ["Y", "N"]),
    ("SP_DUAL_COAT_TYPE", "Dual Coat Type", "SP", "select", None, False,
     ["OVER_COAT", "UNDER_COAT", "NONE"]),
    ("SP_DUAL_PR_TYPE", "Dual PR Type", "SP", "select", None, False,
     ["KrF-A01", "KrF-B02", "ArF-C01", "ArF-D01", "EUV-E01"]),
    ("SP_DUAL_THICKNESS_nm", "Dual PR Thickness", "SP", "float", "nm", False, None),
    ("SP_DUAL_BAKE_TEMP_C", "Dual Bake Temp", "SP", "integer", "\u2103", False, None),
    ("SP_DUAL_BAKE_TIME_sec", "Dual Bake Time", "SP", "integer", "s", False, None),
    ("SP_EDGE_BEAD_WIDTH_mm", "Edge Bead Width", "SP", "float", "mm", False, None),
    ("SP_EDGE_RINSE_WIDTH_mm", "Edge Rinse Width", "SP", "float", "mm", False, None),
    ("SP_EDGE_EXPOSE_WIDTH_mm", "Edge Expose Width", "SP", "float", "mm", False, None),
    ("SP_EDGE_EXCLUDE_mm", "Edge Exclude", "SP", "float", "mm", False, None),
    ("SP_BAKE_RAMP_RATE_C_s", "Bake Ramp Rate", "SP", "float", "\u2103/s", False, None),
    ("SP_BAKE_HOLD_TEMP_C", "Bake Hold Temp", "SP", "integer", "\u2103", False, None),
    ("SP_BAKE_HOLD_TIME_sec", "Bake Hold Time", "SP", "integer", "s", False, None),
    ("SP_COOL_RAMP_RATE_C_s", "Cool Ramp Rate", "SP", "float", "\u2103/s", False, None),
    ("SP_BAKE_UNIFORMITY_C", "Bake Uniformity", "SP", "float", "\u2103", False, None),
    ("SP_DISPENSE_RATE_ml_s", "Dispense Rate", "SP", "float", "ml/s", False, None),
    ("SP_DISPENSE_NOZZLE", "Dispense Nozzle", "SP", "select", None, False,
     ["CENTER", "EDGE", "MULTI", "SCAN"]),
    ("SP_DISPENSE_HEIGHT_mm", "Dispense Height", "SP", "float", "mm", False, None),
    ("SP_DISPENSE_OFFSET_mm", "Dispense Offset", "SP", "float", "mm", False, None),
    ("SP_DISPENSE_ANGLE_deg", "Dispense Angle", "SP", "float", "deg", False, None),
    ("SP_PR_LOT_ID", "PR Lot ID", "SP", "string", None, False, None),
    ("SP_PR_EXPIRY_DAYS", "PR Expiry Days", "SP", "integer", "days", False, None),
    ("SP_PR_FILTER_um", "PR Filter", "SP", "float", "\u03bcm", False, None),
    ("SP_PR_SOLVENT", "PR Solvent", "SP", "select", None, False,
     ["PGMEA", "EL", "PGME", "MAK"]),
    ("SP_PR_SENSITIVITY", "PR Sensitivity", "SP", "select", None, False,
     ["HIGH", "MEDIUM", "LOW"]),
    ("SP_AMBIENT_TEMP_C", "Ambient Temp", "SP", "integer", "\u2103", False, None),
    ("SP_CHUCK_TEMP_C", "Chuck Temp", "SP", "integer", "\u2103", False, None),
    ("SP_EXHAUST_PRESS_Pa", "Exhaust Pressure", "SP", "float", "Pa", False, None),
    ("SP_CDA_FLOW_L_min", "CDA Flow", "SP", "float", "L/min", False, None),
    ("SP_N2_PURGE_USE", "N2 Purge Use", "SP", "select", None, False, ["Y", "N"]),
    ("SP_SPIN3_SPEED_rpm", "Spin3 Speed", "SP", "integer", "rpm", False, None),
    ("SP_SPIN3_TIME_sec", "Spin3 Time", "SP", "integer", "s", False, None),
    ("SP_SPIN3_ACCEL_rpm_s", "Spin3 Accel", "SP", "integer", "rpm/s", False, None),
    ("SP_SPIN1_ACCEL_rpm_s", "Spin1 Accel", "SP", "integer", "rpm/s", False, None),
    ("SP_SPIN2_ACCEL_rpm_s", "Spin2 Accel", "SP", "integer", "rpm/s", False, None),
    ("SP_PR_BATCH_ID", "PR Batch ID", "SP", "string", None, False, None),
    ("SP_COAT_RECIPE_ID", "Coat Recipe ID", "SP", "string", None, False, None),
    ("SP_TRACK_TOOL_ID", "Track Tool ID", "SP", "select", None, False,
     ["TEL-ACT12-01", "TEL-ACT12-02", "LAM-SOLA-01", "SCREEN-SK-01"]),
    ("SP_COAT_PASS_COUNT", "Coat Pass Count", "SP", "integer", None, False, None),
    ("SP_BSR_TIME_sec", "BSR Time", "SP", "integer", "s", False, None),
    ("SP_BSR_SPEED_rpm", "BSR Speed", "SP", "integer", "rpm", False, None),
    ("SP_SOLVENT_TYPE", "Solvent Type", "SP", "select", None, False,
     ["PGMEA", "EL", "PGME", "THINNER"]),
    ("SP_PREWET_USE", "Prewet Use", "SP", "select", None, False, ["Y", "N"]),
    ("SP_PREWET_VOL_ml", "Prewet Volume", "SP", "float", "ml", False, None),
    ("SP_PREWET_TIME_sec", "Prewet Time", "SP", "integer", "s", False, None),
    # --- 보충 SP 컬럼 (10개 추가 -> SP 총 85개): 노즐, 스핀 램프, 칠 플레이트 등 ---
    ("SP_NOZZLE_MATERIAL", "Nozzle Material", "SP", "select", None, False,
     ["PTFE", "PEEK", "SS316", "CERAMIC"]),
    ("SP_SPIN_RAMP_TIME_sec", "Spin Ramp Time", "SP", "integer", "s", False, None),
    ("SP_SPIN_HOLD_TIME_sec", "Spin Hold Time", "SP", "integer", "s", False, None),
    ("SP_PR_BATCH_SIZE", "PR Batch Size", "SP", "integer", None, False, None),
    ("SP_CHILL_PLATE_TEMP_C", "Chill Plate Temp", "SP", "integer", "\u2103", False, None),
    ("SP_CHILL_PLATE_TIME_sec", "Chill Plate Time", "SP", "integer", "s", False, None),
    ("SP_COAT_ARM_SPEED_rpm_s", "Coat Arm Speed", "SP", "float", "rpm/s", False, None),
    ("SP_DISPENSE_TEMP_C", "Dispense Temp", "SP", "float", "\u2103", False, None),
    ("SP_PR_AGED_DAYS", "PR Aged Days", "SP", "integer", "days", False, None),
    ("SP_SPIN_CUP_TYPE", "Spin Cup Type", "SP", "select", None, False,
     ["OPEN", "CLOSED", "EXHAUST"]),

    # -----------------------------------------------------------------------
    # SC 카테고리 (~90개 컬럼): 스캐너/노광 공정 파라미터
    # 노광 에너지, 포커스, 조명 모드, 정렬, 레티클, EUV 설정 등
    # -----------------------------------------------------------------------
    # --- 기존 19개 SC 컬럼 ---
    ("SC_TOOL_ID", "Scanner Tool", "SC", "select", None, True, SCANNER_TOOL_OPTIONS),
    ("SC_RETICLE_ID", "Reticle ID", "SC", "string", None, True, None),
    ("SC_EXPOSE_ENERGY_mJ", "Expose Energy", "SC", "float", "mJ", True, None),
    ("SC_EXPOSE_FOCUS_um", "Expose Focus", "SC", "float", "\u03bcm", True, None),
    ("SC_ILLUM_MODE", "Illumination Mode", "SC", "select", None, True,
     ["CONVENTIONAL", "ANNULAR", "DIPOLE_X", "DIPOLE_Y", "QUASAR", "CQUAD"]),
    ("SC_ILLUM_SIGMA_IN", "Sigma Inner", "SC", "float", None, False, None),
    ("SC_ILLUM_SIGMA_OUT", "Sigma Outer", "SC", "float", None, False, None),
    ("SC_NA", "NA", "SC", "float", None, True, None),
    ("SC_DOSE_TOLERANCE_PCT", "Dose Tolerance", "SC", "float", "%", False, None),
    ("SC_ALIGN_MARK_TYPE", "Align Mark Type", "SC", "select", None, False,
     ["SSA", "LSA", "ATHENA", "SMASH"]),
    ("SC_ALIGN_TREE", "Align Tree", "SC", "string", None, False, None),
    ("SC_EXPOSE_MODE", "Expose Mode", "SC", "select", None, False,
     ["STEP_SCAN", "STEP_REPEAT"]),
    ("SC_SCAN_DIRECTION", "Scan Direction", "SC", "select", None, False,
     ["IN_SCAN", "OUT_SCAN", "BOTH"]),
    ("SC_SLIT_WIDTH_mm", "Slit Width", "SC", "float", "mm", False, None),
    ("SC_RETICLE_CORR_X_nm", "Reticle Corr X", "SC", "float", "nm", False, None),
    ("SC_RETICLE_CORR_Y_nm", "Reticle Corr Y", "SC", "float", "nm", False, None),
    ("SC_WAVELENGTH_nm", "Wavelength", "SC", "select", "nm", True, [248, 193, 13]),
    ("SC_MASK_TYPE", "Mask Type", "SC", "select", None, False,
     ["BINARY", "PSM", "EAPSM", "ALTPSM"]),
    ("SC_IMMERSION", "Immersion", "SC", "select", None, False, ["Y", "N"]),
    # --- 추가 SC 컬럼 (~71개): 수차 보정, Dose/Focus 맵, 샷 크기, EUV 전용 설정 등 ---
    ("SC_ABER_COMA_X", "Aberration Coma X", "SC", "float", "nm", False, None),
    ("SC_ABER_COMA_Y", "Aberration Coma Y", "SC", "float", "nm", False, None),
    ("SC_ABER_ASTIG_X", "Aberration Astig X", "SC", "float", "nm", False, None),
    ("SC_ABER_ASTIG_Y", "Aberration Astig Y", "SC", "float", "nm", False, None),
    ("SC_ABER_TREFOIL", "Aberration Trefoil", "SC", "float", "nm", False, None),
    ("SC_ABER_SPHERICAL", "Aberration Spherical", "SC", "float", "nm", False, None),
    ("SC_ABER_FIELD_CURV", "Aberration Field Curv", "SC", "float", "nm", False, None),
    ("SC_DOSE_MAP_TYPE", "Dose Map Type", "SC", "select", None, False,
     ["UNIFORM", "GRID", "FIELD", "NONE"]),
    ("SC_DOSE_MAP_POINTS", "Dose Map Points", "SC", "integer", None, False, None),
    ("SC_FOCUS_MAP_TYPE", "Focus Map Type", "SC", "select", None, False,
     ["UNIFORM", "GRID", "FIELD", "NONE"]),
    ("SC_FOCUS_MAP_POINTS", "Focus Map Points", "SC", "integer", None, False, None),
    ("SC_DOSE_CORR_PCT", "Dose Correction", "SC", "float", "%", False, None),
    ("SC_FOCUS_CORR_um", "Focus Correction", "SC", "float", "\u03bcm", False, None),
    ("SC_DOSE_UNIFORMITY_PCT", "Dose Uniformity", "SC", "float", "%", False, None),
    ("SC_SHOT_SIZE_X_mm", "Shot Size X", "SC", "float", "mm", False, None),
    ("SC_SHOT_SIZE_Y_mm", "Shot Size Y", "SC", "float", "mm", False, None),
    ("SC_SHOT_OFFSET_X_mm", "Shot Offset X", "SC", "float", "mm", False, None),
    ("SC_SHOT_OFFSET_Y_mm", "Shot Offset Y", "SC", "float", "mm", False, None),
    ("SC_FIELD_SIZE_X_mm", "Field Size X", "SC", "float", "mm", False, None),
    ("SC_FIELD_SIZE_Y_mm", "Field Size Y", "SC", "float", "mm", False, None),
    ("SC_SHOT_ROTATION_mrad", "Shot Rotation", "SC", "float", "mrad", False, None),
    ("SC_ALIGN_CORR_X_nm", "Align Correction X", "SC", "float", "nm", False, None),
    ("SC_ALIGN_CORR_Y_nm", "Align Correction Y", "SC", "float", "nm", False, None),
    ("SC_ALIGN_ROTATION_urad", "Align Rotation", "SC", "float", "\u03bcrad", False, None),
    ("SC_ALIGN_MAG_PPM", "Align Magnification", "SC", "float", "ppm", False, None),
    ("SC_WAFER_ROTATION_urad", "Wafer Rotation", "SC", "float", "\u03bcrad", False, None),
    ("SC_ALIGN_SEQ", "Align Sequence", "SC", "string", None, False, None),
    ("SC_FOCUS_TILT_X_nm", "Focus Tilt X", "SC", "float", "nm", False, None),
    ("SC_FOCUS_TILT_Y_nm", "Focus Tilt Y", "SC", "float", "nm", False, None),
    ("SC_FOCUS_OFFSET_nm", "Focus Offset", "SC", "float", "nm", False, None),
    ("SC_LEVEL_SENSOR_MODE", "Level Sensor Mode", "SC", "select", None, False,
     ["AUTO", "MANUAL", "FIXED"]),
    ("SC_FOCUS_EXPO_MODE", "Focus Expo Mode", "SC", "select", None, False,
     ["BEST", "FIXED", "MAP"]),
    ("SC_GLOBAL_FOCUS_nm", "Global Focus", "SC", "float", "nm", False, None),
    ("SC_PELLICLE_USE", "Pellicle Use", "SC", "select", None, False, ["Y", "N"]),
    ("SC_PELLICLE_TYPE", "Pellicle Type", "SC", "select", None, False,
     ["FSI", "MFS", "EUV-PELLICLE", "NONE"]),
    ("SC_PELLICLE_TRANS_PCT", "Pellicle Transmission", "SC", "float", "%", False, None),
    ("SC_EUV_POWER_W", "EUV Power", "SC", "float", "W", False, None),
    ("SC_EUV_DOSE_RATE", "EUV Dose Rate", "SC", "float", None, False, None),
    ("SC_EUV_FLARE_PCT", "EUV Flare", "SC", "float", "%", False, None),
    ("SC_EUV_STOCHASTIC_MODE", "EUV Stochastic Mode", "SC", "select", None, False,
     ["STANDARD", "ENHANCED", "NONE"]),
    ("SC_EUV_MASK_3D_CORR", "EUV Mask 3D Correction", "SC", "select", None, False,
     ["Y", "N"]),
    ("SC_RETICLE_QUAL_DATE", "Reticle Qual Date", "SC", "string", None, False, None),
    ("SC_RETICLE_USAGE_COUNT", "Reticle Usage Count", "SC", "integer", None, False, None),
    ("SC_BATCH_ID", "Batch ID", "SC", "string", None, False, None),
    ("SC_RECIPE_ID", "Recipe ID", "SC", "string", None, False, None),
    ("SC_EXPOSE_PASSES", "Expose Passes", "SC", "integer", None, False, None),
    ("SC_MULTI_EXPOSE_USE", "Multi Expose Use", "SC", "select", None, False, ["Y", "N"]),
    ("SC_BASELINE_ENERGY_mJ", "Baseline Energy", "SC", "float", "mJ", False, None),
    ("SC_BASELINE_FOCUS_um", "Baseline Focus", "SC", "float", "\u03bcm", False, None),
    ("SC_SCAN_SPEED_mm_s", "Scan Speed", "SC", "float", "mm/s", False, None),
    ("SC_SLIT_PROFILE", "Slit Profile", "SC", "select", None, False,
     ["UNIFORM", "SHAPED", "CUSTOM"]),
    ("SC_PUPIL_FILL", "Pupil Fill", "SC", "float", "%", False, None),
    ("SC_SOURCE_SHAPE", "Source Shape", "SC", "select", None, False,
     ["CIRCULAR", "ANNULAR", "DIPOLE", "QUADRUPOLE", "FREEFORM"]),
    ("SC_PELLICLE_FRAME_ID", "Pellicle Frame ID", "SC", "string", None, False, None),
    ("SC_RETICLE_CD_nm", "Reticle CD", "SC", "float", "nm", False, None),
    ("SC_DEFOCUS_BUDGET_nm", "Defocus Budget", "SC", "float", "nm", False, None),
    ("SC_DOSE_LATITUDE_PCT", "Dose Latitude", "SC", "float", "%", False, None),
    ("SC_FOCUS_LATITUDE_um", "Focus Latitude", "SC", "float", "\u03bcm", False, None),
    ("SC_NILS", "NILS", "SC", "float", None, False, None),
    ("SC_MEF", "MEF", "SC", "float", None, False, None),
    ("SC_THPUT_WPH", "Throughput", "SC", "float", "wph", False, None),
    ("SC_IMAGE_LOG_SLOPE", "Image Log Slope", "SC", "float", None, False, None),
    # --- 보충 SC 컬럼 (9개 추가 -> SC 총 90개): 포커스 드리프트, 렌즈 보정, 웨이퍼 수 등 ---
    ("SC_FOCUS_DRIFT_nm_hr", "Focus Drift", "SC", "float", "nm/hr", False, None),
    ("SC_DOSE_DRIFT_PCT_hr", "Dose Drift", "SC", "float", "%/hr", False, None),
    ("SC_RETICLE_HEAT_CORR", "Reticle Heat Correction", "SC", "select", None, False, ["Y", "N"]),
    ("SC_LENS_HEAT_CORR", "Lens Heat Correction", "SC", "select", None, False, ["Y", "N"]),
    ("SC_WAFER_STAGE_TEMP_C", "Wafer Stage Temp", "SC", "float", "\u2103", False, None),
    ("SC_ILLUM_UNIFORMITY_PCT", "Illumination Uniformity", "SC", "float", "%", False, None),
    ("SC_RETICLE_FLATNESS_nm", "Reticle Flatness", "SC", "float", "nm", False, None),
    ("SC_SHOT_COUNT", "Shot Count", "SC", "integer", None, False, None),
    ("SC_WAFER_COUNT", "Wafer Count", "SC", "integer", None, False, None),

    # -----------------------------------------------------------------------
    # OVL 카테고리 (~80개 컬럼): 오버레이(정렬) 공정 파라미터
    # OVL 스펙, 참조 레이어, 보정값, APC, 측정 조건, SPC 관리 한계 등
    # -----------------------------------------------------------------------
    # --- 기존 14개 OVL 컬럼 ---
    ("OVL_SPEC_X_nm", "OVL Spec X", "OVL", "float", "nm", True, None),
    ("OVL_SPEC_Y_nm", "OVL Spec Y", "OVL", "float", "nm", True, None),
    ("OVL_REF_LAYER", "Reference Layer", "OVL", "layer_ref", None, False, None),
    ("OVL_CORRECT_X_nm", "Correction X", "OVL", "float", "nm", False, None),
    ("OVL_CORRECT_Y_nm", "Correction Y", "OVL", "float", "nm", False, None),
    ("OVL_APC_USE", "APC Use", "OVL", "select", None, False, ["Y", "N"]),
    ("OVL_APC_TYPE", "APC Type", "OVL", "select", None, False,
     ["LINEAR", "HIGHER_ORDER", "INTRAFIELD"]),
    ("OVL_MEAS_TOOL", "Meas Tool", "OVL", "select", None, False,
     ["ARCHER-500", "ARCHER-600", "YS-350"]),
    ("OVL_MEAS_POINT_COUNT", "Meas Points", "OVL", "integer", None, False, None),
    ("OVL_SAMPLING_MODE", "Sampling Mode", "OVL", "select", None, False,
     ["FULL", "SPARSE", "EDGE"]),
    ("OVL_REG_MODEL", "Reg Model", "OVL", "select", None, False,
     ["6PAR", "10PAR", "HIGHER"]),
    ("OVL_FEEDBACK_USE", "Feedback Use", "OVL", "select", None, False, ["Y", "N"]),
    ("OVL_FEEDFORWARD_USE", "Feedforward Use", "OVL", "select", None, False, ["Y", "N"]),
    ("OVL_TARGET_TYPE", "Target Type", "OVL", "select", None, False,
     ["uDBO", "AIM", "AIMplus"]),
    # --- 추가 OVL 컬럼 (~66개): 다중 참조, 웨이퍼 휨/워프, 공정 시프트, 측정 파라미터, SPC 등 ---
    ("OVL_REF_LAYER_2", "Reference Layer 2", "OVL", "layer_ref", None, False, None),
    ("OVL_REF_LAYER_3", "Reference Layer 3", "OVL", "layer_ref", None, False, None),
    ("OVL_REF_WEIGHT_1", "Ref Weight 1", "OVL", "float", None, False, None),
    ("OVL_REF_WEIGHT_2", "Ref Weight 2", "OVL", "float", None, False, None),
    ("OVL_REF_WEIGHT_3", "Ref Weight 3", "OVL", "float", None, False, None),
    ("OVL_CORR_3RD_X", "Correction 3rd X", "OVL", "float", "nm", False, None),
    ("OVL_CORR_3RD_Y", "Correction 3rd Y", "OVL", "float", "nm", False, None),
    ("OVL_CORR_ROTATION_urad", "Correction Rotation", "OVL", "float", "\u03bcrad", False, None),
    ("OVL_CORR_MAG_PPM", "Correction Magnification", "OVL", "float", "ppm", False, None),
    ("OVL_CORR_ASYM_X", "Correction Asymmetry X", "OVL", "float", "nm", False, None),
    ("OVL_CORR_ASYM_Y", "Correction Asymmetry Y", "OVL", "float", "nm", False, None),
    ("OVL_INTRAFIELD_CORR_USE", "Intrafield Correction Use", "OVL", "select", None, False, ["Y", "N"]),
    ("OVL_WAFER_BOW_um", "Wafer Bow", "OVL", "float", "\u03bcm", False, None),
    ("OVL_WAFER_WARP_um", "Wafer Warp", "OVL", "float", "\u03bcm", False, None),
    ("OVL_STRESS_CORR_USE", "Stress Correction Use", "OVL", "select", None, False, ["Y", "N"]),
    ("OVL_THERMAL_CORR_USE", "Thermal Correction Use", "OVL", "select", None, False, ["Y", "N"]),
    ("OVL_CMP_CORR_USE", "CMP Correction Use", "OVL", "select", None, False, ["Y", "N"]),
    ("OVL_ETCH_SHIFT_X_nm", "Etch Shift X", "OVL", "float", "nm", False, None),
    ("OVL_ETCH_SHIFT_Y_nm", "Etch Shift Y", "OVL", "float", "nm", False, None),
    ("OVL_DEP_SHIFT_X_nm", "Dep Shift X", "OVL", "float", "nm", False, None),
    ("OVL_DEP_SHIFT_Y_nm", "Dep Shift Y", "OVL", "float", "nm", False, None),
    ("OVL_CMP_SHIFT_X_nm", "CMP Shift X", "OVL", "float", "nm", False, None),
    ("OVL_CMP_SHIFT_Y_nm", "CMP Shift Y", "OVL", "float", "nm", False, None),
    ("OVL_MEAS_RECIPE_ID", "Meas Recipe ID", "OVL", "string", None, False, None),
    ("OVL_MEAS_WAVELENGTH_nm", "Meas Wavelength", "OVL", "float", "nm", False, None),
    ("OVL_MEAS_ANGLE_deg", "Meas Angle", "OVL", "float", "deg", False, None),
    ("OVL_MEAS_AZIMUTH_deg", "Meas Azimuth", "OVL", "float", "deg", False, None),
    ("OVL_MEAS_FOCUS_um", "Meas Focus", "OVL", "float", "\u03bcm", False, None),
    ("OVL_MEAS_SPOT_SIZE_um", "Meas Spot Size", "OVL", "float", "\u03bcm", False, None),
    ("OVL_SPC_UCL_X_nm", "SPC UCL X", "OVL", "float", "nm", False, None),
    ("OVL_SPC_LCL_X_nm", "SPC LCL X", "OVL", "float", "nm", False, None),
    ("OVL_SPC_UCL_Y_nm", "SPC UCL Y", "OVL", "float", "nm", False, None),
    ("OVL_SPC_LCL_Y_nm", "SPC LCL Y", "OVL", "float", "nm", False, None),
    ("OVL_SPC_MEAN_SHIFT_X", "SPC Mean Shift X", "OVL", "float", "nm", False, None),
    ("OVL_SPC_MEAN_SHIFT_Y", "SPC Mean Shift Y", "OVL", "float", "nm", False, None),
    ("OVL_MARK_LAYER", "Mark Layer", "OVL", "string", None, False, None),
    ("OVL_MARK_DESIGN", "Mark Design", "OVL", "select", None, False,
     ["BOX_IN_BOX", "FRAME_IN_FRAME", "AIM_MARK", "DBO"]),
    ("OVL_MARK_SIZE_um", "Mark Size", "OVL", "float", "\u03bcm", False, None),
    ("OVL_MARK_PITCH_um", "Mark Pitch", "OVL", "float", "\u03bcm", False, None),
    ("OVL_DBO_NUM_PADS", "DBO Num Pads", "OVL", "integer", None, False, None),
    ("OVL_DBO_PAD_SIZE_um", "DBO Pad Size", "OVL", "float", "\u03bcm", False, None),
    ("OVL_CORR_METHOD", "Correction Method", "OVL", "select", None, False,
     ["CPE", "HPE", "FIELD_BY_FIELD"]),
    ("OVL_CORR_MODEL_VER", "Correction Model Ver", "OVL", "string", None, False, None),
    ("OVL_FEEDBACK_GAIN", "Feedback Gain", "OVL", "float", None, False, None),
    ("OVL_FF_GAIN", "Feedforward Gain", "OVL", "float", None, False, None),
    ("OVL_BATCH_ID", "OVL Batch ID", "OVL", "string", None, False, None),
    ("OVL_MEAS_PASS_COUNT", "Meas Pass Count", "OVL", "integer", None, False, None),
    ("OVL_MEAS_SITE_X", "Meas Site X", "OVL", "integer", None, False, None),
    ("OVL_MEAS_SITE_Y", "Meas Site Y", "OVL", "integer", None, False, None),
    ("OVL_TIS_X_nm", "TIS X", "OVL", "float", "nm", False, None),
    ("OVL_TIS_Y_nm", "TIS Y", "OVL", "float", "nm", False, None),
    ("OVL_WIS_X_nm", "WIS X", "OVL", "float", "nm", False, None),
    ("OVL_WIS_Y_nm", "WIS Y", "OVL", "float", "nm", False, None),
    ("OVL_RESI_3SIGMA_X_nm", "Residual 3Sigma X", "OVL", "float", "nm", False, None),
    ("OVL_RESI_3SIGMA_Y_nm", "Residual 3Sigma Y", "OVL", "float", "nm", False, None),
    ("OVL_RESI_MAX_X_nm", "Residual Max X", "OVL", "float", "nm", False, None),
    ("OVL_RESI_MAX_Y_nm", "Residual Max Y", "OVL", "float", "nm", False, None),
    ("OVL_MMO_X_nm", "MMO X", "OVL", "float", "nm", False, None),
    ("OVL_MMO_Y_nm", "MMO Y", "OVL", "float", "nm", False, None),
    ("OVL_SPEC_VECTOR_nm", "Spec Vector", "OVL", "float", "nm", False, None),
    ("OVL_GOLDEN_REF_USE", "Golden Ref Use", "OVL", "select", None, False, ["Y", "N"]),
    # --- 보충 OVL 컬럼 (5개 추가 -> OVL 총 80개): 필드 회전, 교정 날짜, 장비 유발 시프트 ---
    ("OVL_FIELD_ROTATION_urad", "Field Rotation", "OVL", "float", "\u03bcrad", False, None),
    ("OVL_FIELD_MAG_PPM", "Field Magnification", "OVL", "float", "ppm", False, None),
    ("OVL_CALIB_DATE", "Calibration Date", "OVL", "string", None, False, None),
    ("OVL_TOOL_INDUCED_SHIFT_X", "Tool Induced Shift X", "OVL", "float", "nm", False, None),
    ("OVL_TOOL_INDUCED_SHIFT_Y", "Tool Induced Shift Y", "OVL", "float", "nm", False, None),

    # -----------------------------------------------------------------------
    # DEV 카테고리 (~95개 컬럼): 현상(Develop) 공정 파라미터
    # 현상액 종류, 퍼들 시간, CD 타겟/스펙, 검사 장비, 재작업 조건 등
    # -----------------------------------------------------------------------
    # --- 기존 14개 DEV 컬럼 ---
    ("DEV_TYPE", "Developer Type", "DEV", "select", None, True,
     ["NMD-3", "TMAH_2.38", "NMD-W", "AZ300MIF"]),
    ("DEV_PUDDLE_TIME_sec", "Puddle Time", "DEV", "integer", "s", True, None),
    ("DEV_PUDDLE_COUNT", "Puddle Count", "DEV", "select", None, False, [1, 2, 3]),
    ("DEV_RINSE_TYPE", "Rinse Type", "DEV", "select", None, False,
     ["DI_WATER", "SURFACTANT", "SOLVENT"]),
    ("DEV_RINSE_TIME_sec", "Rinse Time", "DEV", "integer", "s", False, None),
    ("DEV_POSTBAKE_TEMP_C", "Postbake Temp", "DEV", "integer", "\u2103", False, None),
    ("DEV_POSTBAKE_TIME_sec", "Postbake Time", "DEV", "integer", "s", False, None),
    ("DEV_CD_TARGET_nm", "CD Target", "DEV", "float", "nm", False, None),
    ("DEV_CD_SPEC_LOW_nm", "CD Spec Lower", "DEV", "float", "nm", False, None),
    ("DEV_CD_SPEC_HIGH_nm", "CD Spec Upper", "DEV", "float", "nm", False, None),
    ("DEV_CD_MEAS_TOOL", "CD Meas Tool", "DEV", "select", None, False,
     ["CD-SEM-01", "CD-SEM-02", "OCD-01"]),
    ("DEV_CD_MEAS_POINTS", "CD Meas Points", "DEV", "integer", None, False, None),
    ("DEV_INSPECT_TOOL", "Inspect Tool", "DEV", "select", None, False,
     ["KLA-2810", "KLA-2815", "KLA-Puma"]),
    ("DEV_DEFECT_SPEC", "Defect Spec", "DEV", "integer", None, False, None),
    # --- 추가 DEV 컬럼 (~81개): OCD/AFM 측정, 결함 분류, 재작업, PEB, SPC, 패턴 붕괴 등 ---
    ("DEV_OCD_USE", "OCD Use", "DEV", "select", None, False, ["Y", "N"]),
    ("DEV_OCD_TOOL", "OCD Tool", "DEV", "select", None, False,
     ["OCD-01", "OCD-02", "NOVA-T600", "NONE"]),
    ("DEV_OCD_RECIPE", "OCD Recipe", "DEV", "string", None, False, None),
    ("DEV_OCD_SITE_COUNT", "OCD Site Count", "DEV", "integer", None, False, None),
    ("DEV_OCD_MODEL", "OCD Model", "DEV", "string", None, False, None),
    ("DEV_AFM_USE", "AFM Use", "DEV", "select", None, False, ["Y", "N"]),
    ("DEV_AFM_TOOL", "AFM Tool", "DEV", "select", None, False,
     ["AFM-01", "DIMENSION-3100", "NONE"]),
    ("DEV_AFM_SCAN_SIZE_um", "AFM Scan Size", "DEV", "float", "\u03bcm", False, None),
    ("DEV_AFM_SCAN_RATE_Hz", "AFM Scan Rate", "DEV", "float", "Hz", False, None),
    ("DEV_DEFECT_CLASS_USE", "Defect Class Use", "DEV", "select", None, False, ["Y", "N"]),
    ("DEV_DEFECT_CLASS_RECIPE", "Defect Class Recipe", "DEV", "string", None, False, None),
    ("DEV_DEFECT_REVIEW_TOOL", "Defect Review Tool", "DEV", "select", None, False,
     ["KLA-2810", "KLA-Puma", "REVIEW-SEM-01"]),
    ("DEV_DEFECT_REVIEW_COUNT", "Defect Review Count", "DEV", "integer", None, False, None),
    ("DEV_DEFECT_KILLER_PCT", "Defect Killer Pct", "DEV", "float", "%", False, None),
    ("DEV_DEFECT_NUISANCE_PCT", "Defect Nuisance Pct", "DEV", "float", "%", False, None),
    ("DEV_REWORK_SPEC_USE", "Rework Spec Use", "DEV", "select", None, False, ["Y", "N"]),
    ("DEV_REWORK_CD_LOW_nm", "Rework CD Low", "DEV", "float", "nm", False, None),
    ("DEV_REWORK_CD_HIGH_nm", "Rework CD High", "DEV", "float", "nm", False, None),
    ("DEV_REWORK_OVL_LIMIT_nm", "Rework OVL Limit", "DEV", "float", "nm", False, None),
    ("DEV_REWORK_DEFECT_LIMIT", "Rework Defect Limit", "DEV", "integer", None, False, None),
    ("DEV_REWORK_METHOD", "Rework Method", "DEV", "select", None, False,
     ["STRIP_RECOAT", "FULL_REWORK", "NONE"]),
    ("DEV_POST_ETCH_CD_nm", "Post Etch CD", "DEV", "float", "nm", False, None),
    ("DEV_POST_ETCH_PROFILE_deg", "Post Etch Profile", "DEV", "float", "deg", False, None),
    ("DEV_POST_ETCH_DEPTH_nm", "Post Etch Depth", "DEV", "float", "nm", False, None),
    ("DEV_POST_ETCH_MEAS_TOOL", "Post Etch Meas Tool", "DEV", "select", None, False,
     ["CD-SEM-01", "CD-SEM-02", "OCD-01"]),
    ("DEV_POST_ETCH_SITE_COUNT", "Post Etch Site Count", "DEV", "integer", None, False, None),
    ("DEV_SPC_CD_UCL_nm", "SPC CD UCL", "DEV", "float", "nm", False, None),
    ("DEV_SPC_CD_LCL_nm", "SPC CD LCL", "DEV", "float", "nm", False, None),
    ("DEV_SPC_CD_TARGET_nm", "SPC CD Target", "DEV", "float", "nm", False, None),
    ("DEV_SPC_UNIFORMITY_PCT", "SPC Uniformity", "DEV", "float", "%", False, None),
    ("DEV_SPC_RANGE_nm", "SPC Range", "DEV", "float", "nm", False, None),
    ("DEV_TEMP_C", "Dev Temp", "DEV", "integer", "\u2103", False, None),
    ("DEV_FLOW_RATE_ml_s", "Dev Flow Rate", "DEV", "float", "ml/s", False, None),
    ("DEV_NOZZLE_TYPE", "Dev Nozzle Type", "DEV", "select", None, False,
     ["STANDARD", "SCAN", "PADDLE", "PUDDLE"]),
    ("DEV_NOZZLE_SCAN_SPEED_mm_s", "Nozzle Scan Speed", "DEV", "float", "mm/s", False, None),
    ("DEV_NOZZLE_GAP_mm", "Nozzle Gap", "DEV", "float", "mm", False, None),
    ("DEV_DISPENSE_MODE", "Dev Dispense Mode", "DEV", "select", None, False,
     ["STATIC", "DYNAMIC", "SPRAY"]),
    ("DEV_SPIN_SPEED_rpm", "Dev Spin Speed", "DEV", "integer", "rpm", False, None),
    ("DEV_SPIN_TIME_sec", "Dev Spin Time", "DEV", "integer", "s", False, None),
    ("DEV_PEB_TEMP_C", "PEB Temp", "DEV", "integer", "\u2103", False, None),
    ("DEV_PEB_TIME_sec", "PEB Time", "DEV", "integer", "s", False, None),
    ("DEV_PEB_RAMP_RATE_C_s", "PEB Ramp Rate", "DEV", "float", "\u2103/s", False, None),
    ("DEV_PEB_UNIFORMITY_C", "PEB Uniformity", "DEV", "float", "\u2103", False, None),
    ("DEV_PEB_DELAY_sec", "PEB Delay", "DEV", "integer", "s", False, None),
    ("DEV_PROFILE_ANGLE_deg", "Profile Angle", "DEV", "float", "deg", False, None),
    ("DEV_SIDEWALL_ANGLE_deg", "Sidewall Angle", "DEV", "float", "deg", False, None),
    ("DEV_LWR_nm", "LWR", "DEV", "float", "nm", False, None),
    ("DEV_LER_nm", "LER", "DEV", "float", "nm", False, None),
    ("DEV_RESIST_LOSS_nm", "Resist Loss", "DEV", "float", "nm", False, None),
    ("DEV_PATTERN_COLLAPSE_USE", "Pattern Collapse Check", "DEV", "select", None, False, ["Y", "N"]),
    ("DEV_CD_UNIFORMITY_PCT", "CD Uniformity", "DEV", "float", "%", False, None),
    ("DEV_CD_3SIGMA_nm", "CD 3Sigma", "DEV", "float", "nm", False, None),
    ("DEV_CD_RANGE_nm", "CD Range", "DEV", "float", "nm", False, None),
    ("DEV_BATCH_ID", "Dev Batch ID", "DEV", "string", None, False, None),
    ("DEV_RECIPE_ID", "Dev Recipe ID", "DEV", "string", None, False, None),
    ("DEV_TRACK_TOOL_ID", "Dev Track Tool ID", "DEV", "select", None, False,
     ["TEL-ACT12-01", "TEL-ACT12-02", "LAM-SOLA-01", "SCREEN-SK-01"]),
    ("DEV_STRIP_USE", "Strip Use", "DEV", "select", None, False, ["Y", "N"]),
    ("DEV_STRIP_METHOD", "Strip Method", "DEV", "select", None, False,
     ["WET", "DRY", "ASHING"]),
    ("DEV_STRIP_TEMP_C", "Strip Temp", "DEV", "integer", "\u2103", False, None),
    ("DEV_STRIP_TIME_sec", "Strip Time", "DEV", "integer", "s", False, None),
    ("DEV_HARD_BAKE_TEMP_C", "Hard Bake Temp", "DEV", "integer", "\u2103", False, None),
    ("DEV_HARD_BAKE_TIME_sec", "Hard Bake Time", "DEV", "integer", "s", False, None),
    ("DEV_DI_RESIST_Mohm", "DI Resistance", "DEV", "float", "M\u03a9", False, None),
    ("DEV_RINSE_FLOW_ml_s", "Rinse Flow", "DEV", "float", "ml/s", False, None),
    ("DEV_RINSE_SPIN_rpm", "Rinse Spin Speed", "DEV", "integer", "rpm", False, None),
    ("DEV_DRY_SPIN_rpm", "Dry Spin Speed", "DEV", "integer", "rpm", False, None),
    ("DEV_DRY_TIME_sec", "Dry Time", "DEV", "integer", "s", False, None),
    # --- 보충 DEV 컬럼 (14개 추가 -> DEV 총 95개): 2차 퍼들, 메가소닉, CD SEM, 브릿지/넥 검사 ---
    ("DEV_PUDDLE2_TIME_sec", "Puddle2 Time", "DEV", "integer", "s", False, None),
    ("DEV_PUDDLE2_TEMP_C", "Puddle2 Temp", "DEV", "integer", "\u2103", False, None),
    ("DEV_MEGA_SONIC_USE", "Mega Sonic Use", "DEV", "select", None, False, ["Y", "N"]),
    ("DEV_MEGA_SONIC_FREQ_kHz", "Mega Sonic Freq", "DEV", "float", "kHz", False, None),
    ("DEV_MEGA_SONIC_POWER_W", "Mega Sonic Power", "DEV", "float", "W", False, None),
    ("DEV_CD_SEM_MODE", "CD SEM Mode", "DEV", "select", None, False,
     ["AUTO", "MANUAL", "SEMI_AUTO"]),
    ("DEV_CD_SEM_VOLTAGE_kV", "CD SEM Voltage", "DEV", "float", "kV", False, None),
    ("DEV_CD_SEM_CURRENT_pA", "CD SEM Current", "DEV", "float", "pA", False, None),
    ("DEV_CD_SITE_X_COUNT", "CD Site X Count", "DEV", "integer", None, False, None),
    ("DEV_CD_SITE_Y_COUNT", "CD Site Y Count", "DEV", "integer", None, False, None),
    ("DEV_BRIDGE_INSPECT_USE", "Bridge Inspect Use", "DEV", "select", None, False, ["Y", "N"]),
    ("DEV_BRIDGE_SPEC_COUNT", "Bridge Spec Count", "DEV", "integer", None, False, None),
    ("DEV_NECK_INSPECT_USE", "Neck Inspect Use", "DEV", "select", None, False, ["Y", "N"]),
    ("DEV_DEFECT_SCAN_SPEED", "Defect Scan Speed", "DEV", "select", None, False,
     ["HIGH", "MEDIUM", "LOW"]),

    # -----------------------------------------------------------------------
    # EQP 카테고리 (60개 컬럼): 레이어별 설비(스캐너) 할당 관리
    # 기존 equipment_assignments 테이블 대신 conditions JSONB 컬럼으로 저장
    # EQP_01 ~ EQP_20: 스캐너 장비명 (select)
    # EQP_01_ET ~ EQP_20_ET: 해당 설비의 노광 에너지 (float, mJ)
    # EQP_01_FOCUS ~ EQP_20_FOCUS: 해당 설비의 포커스 오프셋 (float, um)
    # sort_order: (slot-1)*3 + 1 for name, +2 for ET, +3 for FOCUS
    # -----------------------------------------------------------------------
    *[
        col_def
        for slot in range(1, 21)
        for col_def in [
            (
                f"EQP_{slot:02d}",
                f"Scanner #{slot:02d}",
                "EQP",
                "select",
                None,
                False,
                SCANNER_TOOL_OPTIONS,
            ),
            (
                f"EQP_{slot:02d}_ET",
                f"Scanner #{slot:02d} Energy",
                "EQP",
                "float",
                "mJ",
                False,
                None,
            ),
            (
                f"EQP_{slot:02d}_FOCUS",
                f"Scanner #{slot:02d} Focus",
                "EQP",
                "float",
                "um",
                False,
                None,
            ),
        ]
    ],
]

# ---------------------------------------------------------------------------
# 2. 검증 규칙 (~80개)
# ---------------------------------------------------------------------------
# 각 규칙은 (컬럼명, 규칙타입, 규칙파라미터, 오류메시지) 튜플로 정의
# - range: {"min": 최솟값, "max": 최댓값} - 입력값이 범위를 벗어나면 오류
# - conditional_required: {"condition_column": 조건컬럼, "condition_value": 조건값, "operator": 비교연산자}
#   → 조건컬럼이 특정 값일 때 이 컬럼이 필수가 됨 (예: BARC Use=Y이면 BARC Type 필수)
# - cross_layer: {"check_type": 검증종류} - 레이어 간 교차 검증 (참조 레이어 존재 여부 등)
# 새로운 검증 규칙을 추가할 때 이 리스트에 튜플을 추가하면 됨

VALIDATION_RULES: list[tuple] = [
    # 범위 검증 - SP 카테고리 (스핀 속도, 온도, 시간, 두께 등의 물리적 범위 제한)
    ("SP_SPIN1_SPEED_rpm", "range", {"min": 500, "max": 8000}, "Spin1 Speed\ub294 500~8000 rpm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_SPIN2_SPEED_rpm", "range", {"min": 500, "max": 8000}, "Spin2 Speed\ub294 500~8000 rpm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_PREBAKE_TEMP_C", "range", {"min": 0, "max": 300}, "Prebake \uc628\ub3c4\ub294 0~300\u2103 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_PREBAKE_TIME_sec", "range", {"min": 1, "max": 600}, "Prebake \uc2dc\uac04\uc740 1~600\ucd08 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_ADHESION_TEMP_C", "range", {"min": 0, "max": 200}, "Adhesion \uc628\ub3c4\ub294 0~200\u2103 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_PR_THICKNESS_nm", "range", {"min": 100, "max": 10000}, "PR \ub450\uaed8\ub294 100~10000nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_DISPENSE_VOL_ml", "range", {"min": 0.5, "max": 5.0}, "Dispense \ub7c9\uc740 0.5~5.0ml \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_EXPOSE_ENERGY_mJ", "range", {"min": 1.0, "max": 200.0}, "\ub178\uad11 \uc5d0\ub108\uc9c0\ub294 1~200mJ \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_EXPOSE_FOCUS_um", "range", {"min": -1.0, "max": 1.0}, "\ud3ec\ucee4\uc2a4\ub294 -1.0~1.0\u03bcm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_NA", "range", {"min": 0.1, "max": 1.5}, "NA\ub294 0.1~1.5 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("OVL_SPEC_X_nm", "range", {"min": 0.1, "max": 50.0}, "OVL Spec X\ub294 0.1~50nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("OVL_SPEC_Y_nm", "range", {"min": 0.1, "max": 50.0}, "OVL Spec Y\ub294 0.1~50nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_PUDDLE_TIME_sec", "range", {"min": 5, "max": 300}, "Puddle \uc2dc\uac04\uc740 5~300\ucd08 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_POSTBAKE_TEMP_C", "range", {"min": 0, "max": 300}, "Postbake \uc628\ub3c4\ub294 0~300\u2103 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_CD_TARGET_nm", "range", {"min": 1.0, "max": 5000.0}, "CD Target\uc740 1~5000nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_DEFECT_SPEC", "range", {"min": 0, "max": 1000}, "Defect Spec\uc740 0~1000 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    # 조건부 필수 검증 - 특정 컬럼 값에 따라 다른 컬럼이 필수가 되는 규칙
    ("SP_ADHESION_TYPE", "conditional_required",
     {"condition_column": "SP_ADHESION_USE", "condition_value": "Y", "operator": "equals"},
     "Adhesion Use\uac00 Y\uc77c \ub54c Adhesion Type\uc740 \ud544\uc218\uc785\ub2c8\ub2e4"),
    ("SP_ADHESION_TEMP_C", "conditional_required",
     {"condition_column": "SP_ADHESION_USE", "condition_value": "Y", "operator": "equals"},
     "Adhesion Use\uac00 Y\uc77c \ub54c Adhesion Temp\ub294 \ud544\uc218\uc785\ub2c8\ub2e4"),
    ("OVL_APC_TYPE", "conditional_required",
     {"condition_column": "OVL_APC_USE", "condition_value": "Y", "operator": "equals"},
     "APC Use\uac00 Y\uc77c \ub54c APC Type\uc740 \ud544\uc218\uc785\ub2c8\ub2e4"),
    # 범위 검증 - 추가 SP 컬럼 (BARC/TARC 두께, 온도, 엣지 폭, 분사량 등)
    ("SP_BARC_THICKNESS_nm", "range", {"min": 20, "max": 200}, "BARC \ub450\uaed8\ub294 20~200nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_TARC_THICKNESS_nm", "range", {"min": 20, "max": 150}, "TARC \ub450\uaed8\ub294 20~150nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_BARC_BAKE_TEMP_C", "range", {"min": 150, "max": 300}, "BARC Bake \uc628\ub3c4\ub294 150~300\u2103 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_TARC_BAKE_TEMP_C", "range", {"min": 100, "max": 250}, "TARC Bake \uc628\ub3c4\ub294 100~250\u2103 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_EDGE_BEAD_WIDTH_mm", "range", {"min": 0.5, "max": 5.0}, "Edge Bead Width\ub294 0.5~5.0mm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_EDGE_RINSE_WIDTH_mm", "range", {"min": 0.5, "max": 5.0}, "Edge Rinse Width\ub294 0.5~5.0mm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_DISPENSE_RATE_ml_s", "range", {"min": 0.1, "max": 5.0}, "Dispense Rate\ub294 0.1~5.0 ml/s \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_PREWET_VOL_ml", "range", {"min": 0.1, "max": 3.0}, "Prewet Vol\uc740 0.1~3.0ml \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_SPIN3_SPEED_rpm", "range", {"min": 500, "max": 8000}, "Spin3 Speed\ub294 500~8000 rpm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_AMBIENT_TEMP_C", "range", {"min": 20, "max": 30}, "Ambient Temp\ub294 20~30\u2103 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SP_CHUCK_TEMP_C", "range", {"min": 15, "max": 30}, "Chuck Temp\ub294 15~30\u2103 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    # 조건부 필수 검증 - 추가 SP 컬럼 (BARC/TARC/Prewet 사용 시 관련 항목 필수)
    ("SP_BARC_TYPE", "conditional_required",
     {"condition_column": "SP_BARC_USE", "condition_value": "Y", "operator": "equals"},
     "BARC Use\uac00 Y\uc77c \ub54c BARC Type\uc740 \ud544\uc218\uc785\ub2c8\ub2e4"),
    ("SP_BARC_THICKNESS_nm", "conditional_required",
     {"condition_column": "SP_BARC_USE", "condition_value": "Y", "operator": "equals"},
     "BARC Use\uac00 Y\uc77c \ub54c BARC Thickness\ub294 \ud544\uc218\uc785\ub2c8\ub2e4"),
    ("SP_TARC_TYPE", "conditional_required",
     {"condition_column": "SP_TARC_USE", "condition_value": "Y", "operator": "equals"},
     "TARC Use\uac00 Y\uc77c \ub54c TARC Type\uc740 \ud544\uc218\uc785\ub2c8\ub2e4"),
    ("SP_PREWET_VOL_ml", "conditional_required",
     {"condition_column": "SP_PREWET_USE", "condition_value": "Y", "operator": "equals"},
     "Prewet Use\uac00 Y\uc77c \ub54c Prewet Vol\uc740 \ud544\uc218\uc785\ub2c8\ub2e4"),
    # 범위 검증 - SC 카테고리 (수차 보정, Dose/Focus 보정, EUV 파워, 스캔 속도 등)
    ("SC_ABER_COMA_X", "range", {"min": -5.0, "max": 5.0}, "Coma X\ub294 -5~5nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_ABER_COMA_Y", "range", {"min": -5.0, "max": 5.0}, "Coma Y\ub294 -5~5nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_ABER_ASTIG_X", "range", {"min": -5.0, "max": 5.0}, "Astig X\ub294 -5~5nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_DOSE_CORR_PCT", "range", {"min": -10.0, "max": 10.0}, "Dose Correction\uc740 -10~10% \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_FOCUS_CORR_um", "range", {"min": -0.5, "max": 0.5}, "Focus Correction\uc740 -0.5~0.5\u03bcm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_PELLICLE_TRANS_PCT", "range", {"min": 80.0, "max": 100.0}, "Pellicle Transmission\uc740 80~100% \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_EUV_POWER_W", "range", {"min": 10.0, "max": 500.0}, "EUV Power\ub294 10~500W \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_EUV_FLARE_PCT", "range", {"min": 0.0, "max": 10.0}, "EUV Flare\ub294 0~10% \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_SCAN_SPEED_mm_s", "range", {"min": 100.0, "max": 1000.0}, "Scan Speed\ub294 100~1000 mm/s \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("SC_PUPIL_FILL", "range", {"min": 10.0, "max": 100.0}, "Pupil Fill\uc740 10~100% \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    # 조건부 필수 검증 - SC 카테고리 (EUV 파장 사용 시 Power 필수, Pellicle 사용 시 Type 필수)
    ("SC_EUV_POWER_W", "conditional_required",
     {"condition_column": "SC_WAVELENGTH_nm", "condition_value": 13, "operator": "equals"},
     "EUV \ud30c\uc7a5(13nm) \uc0ac\uc6a9 \uc2dc EUV Power\ub294 \ud544\uc218\uc785\ub2c8\ub2e4"),
    ("SC_PELLICLE_TYPE", "conditional_required",
     {"condition_column": "SC_PELLICLE_USE", "condition_value": "Y", "operator": "equals"},
     "Pellicle Use\uac00 Y\uc77c \ub54c Pellicle Type\uc740 \ud544\uc218\uc785\ub2c8\ub2e4"),
    # 범위 검증 - OVL 카테고리 (웨이퍼 휨, 피드백 게인, 측정 파장, TIS, 스펙 벡터 등)
    ("OVL_WAFER_BOW_um", "range", {"min": -200.0, "max": 200.0}, "Wafer Bow\ub294 -200~200\u03bcm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("OVL_WAFER_WARP_um", "range", {"min": 0.0, "max": 400.0}, "Wafer Warp\ub294 0~400\u03bcm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("OVL_FEEDBACK_GAIN", "range", {"min": 0.0, "max": 1.0}, "Feedback Gain\uc740 0~1.0 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("OVL_FF_GAIN", "range", {"min": 0.0, "max": 1.0}, "Feedforward Gain\uc740 0~1.0 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("OVL_MEAS_WAVELENGTH_nm", "range", {"min": 400.0, "max": 800.0}, "Meas Wavelength\ub294 400~800nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("OVL_MEAS_SPOT_SIZE_um", "range", {"min": 1.0, "max": 50.0}, "Meas Spot Size\ub294 1~50\u03bcm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("OVL_TIS_X_nm", "range", {"min": -5.0, "max": 5.0}, "TIS X\ub294 -5~5nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("OVL_TIS_Y_nm", "range", {"min": -5.0, "max": 5.0}, "TIS Y\ub294 -5~5nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("OVL_SPEC_VECTOR_nm", "range", {"min": 0.1, "max": 100.0}, "Spec Vector\ub294 0.1~100nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    # 범위 검증 - DEV 카테고리 (PEB 온도/시간, 현상 온도, 유량, Hard Bake, CD 균일도 등)
    ("DEV_PEB_TEMP_C", "range", {"min": 80, "max": 200}, "PEB \uc628\ub3c4\ub294 80~200\u2103 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_PEB_TIME_sec", "range", {"min": 30, "max": 300}, "PEB \uc2dc\uac04\uc740 30~300\ucd08 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_PEB_DELAY_sec", "range", {"min": 0, "max": 600}, "PEB Delay\ub294 0~600\ucd08 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_TEMP_C", "range", {"min": 20, "max": 30}, "Dev \uc628\ub3c4\ub294 20~30\u2103 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_FLOW_RATE_ml_s", "range", {"min": 0.1, "max": 5.0}, "Dev Flow Rate\ub294 0.1~5.0 ml/s \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_SPIN_SPEED_rpm", "range", {"min": 100, "max": 3000}, "Dev Spin Speed\ub294 100~3000 rpm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_HARD_BAKE_TEMP_C", "range", {"min": 100, "max": 250}, "Hard Bake \uc628\ub3c4\ub294 100~250\u2103 \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_LWR_nm", "range", {"min": 0.0, "max": 10.0}, "LWR\uc740 0~10nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_LER_nm", "range", {"min": 0.0, "max": 10.0}, "LER\uc740 0~10nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_CD_UNIFORMITY_PCT", "range", {"min": 0.0, "max": 10.0}, "CD Uniformity\ub294 0~10% \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_REWORK_CD_LOW_nm", "range", {"min": 1.0, "max": 5000.0}, "Rework CD Low\ub294 1~5000nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    ("DEV_REWORK_OVL_LIMIT_nm", "range", {"min": 1.0, "max": 100.0}, "Rework OVL Limit\uc740 1~100nm \ubc94\uc704\uc5ec\uc57c \ud569\ub2c8\ub2e4"),
    # 조건부 필수 검증 - DEV 카테고리 (OCD/Rework/Strip 사용 시 관련 항목 필수)
    ("DEV_OCD_RECIPE", "conditional_required",
     {"condition_column": "DEV_OCD_USE", "condition_value": "Y", "operator": "equals"},
     "OCD Use\uac00 Y\uc77c \ub54c OCD Recipe\ub294 \ud544\uc218\uc785\ub2c8\ub2e4"),
    ("DEV_REWORK_METHOD", "conditional_required",
     {"condition_column": "DEV_REWORK_SPEC_USE", "condition_value": "Y", "operator": "equals"},
     "Rework Spec Use\uac00 Y\uc77c \ub54c Rework Method\ub294 \ud544\uc218\uc785\ub2c8\ub2e4"),
    ("DEV_STRIP_METHOD", "conditional_required",
     {"condition_column": "DEV_STRIP_USE", "condition_value": "Y", "operator": "equals"},
     "Strip Use\uac00 Y\uc77c \ub54c Strip Method\ub294 \ud544\uc218\uc785\ub2c8\ub2e4"),
    # 크로스 레이어 검증 - 레이어 간 교차 검증 (참조 레이어 존재, 값 비교 등)
    # reference_exists: 참조 레이어가 프로젝트에 존재하는지 확인
    # compare_layers: 참조 레이어와 현재 레이어의 값을 비교
    ("OVL_REF_LAYER", "cross_layer",
     {"check_type": "reference_exists", "source_column": "OVL_REF_LAYER", "target": "step_seq"},
     "\ucc38\uc870 \ub808\uc774\uc5b4\uac00 \ud504\ub85c\uc81d\ud2b8\uc5d0 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4"),
    ("OVL_SPEC_VECTOR_nm", "cross_layer",
     {"check_type": "compare_layers", "column": "OVL_SPEC_VECTOR_nm",
      "operator": "<=", "reference_layer_column": "OVL_REF_LAYER", "threshold_ratio": 1.2},
     "OVL Spec\uc774 \ucc38\uc870 \ub808\uc774\uc5b4 \ub300\ube44 \uae30\uc900\uc744 \ucd08\uacfc\ud569\ub2c8\ub2e4"),
]
