"""백본 layer matching and snapshot contracts."""

from app.domain.backbone.matching import (
    LayerMatchInput,
    ManualOverride,
    MatchResult,
    match_layers,
)
from app.domain.backbone.snapshot import (
    BASELINE_UNAVAILABLE,
    INVALID_BACKBONE_SNAPSHOT,
    SNAPSHOT_VERSION,
    UNRESOLVED_PARAMETER_METADATA,
    BackboneSnapshot,
    BackboneSnapshotCell,
    BackboneSnapshotColumn,
    BackboneSnapshotCondition,
    BackboneSnapshotSource,
    backbone_snapshot_hash,
    format_captured_at,
    new_capture_batch_id,
    normalize_capture_batch_id,
    normalize_captured_at,
    parse_backbone_snapshot,
    serialize_backbone_snapshot,
    snapshot,
)

__all__ = [
    "BASELINE_UNAVAILABLE",
    "BackboneSnapshot",
    "BackboneSnapshotCell",
    "BackboneSnapshotColumn",
    "BackboneSnapshotCondition",
    "BackboneSnapshotSource",
    "INVALID_BACKBONE_SNAPSHOT",
    "LayerMatchInput",
    "ManualOverride",
    "MatchResult",
    "SNAPSHOT_VERSION",
    "UNRESOLVED_PARAMETER_METADATA",
    "backbone_snapshot_hash",
    "format_captured_at",
    "match_layers",
    "new_capture_batch_id",
    "normalize_capture_batch_id",
    "normalize_captured_at",
    "parse_backbone_snapshot",
    "serialize_backbone_snapshot",
    "snapshot",
]
